import "./globals.css";
import { UserProvider } from "@/providers/User";
import type { Metadata } from "next";
import { Roboto_Flex, Bai_Jamjuree, Anton } from "next/font/google";

const roboto = Roboto_Flex({ subsets: ["latin"], variable: "--font-roboto" });
const anton = Anton({
  subsets: ["latin"],
  variable: "--font-anton",
  weight: "400",
});

const baiJamJuree = Bai_Jamjuree({
  subsets: ["latin"],
  weight: "700",
  variable: "--font-bailjamjuree",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body
        className={`${roboto.variable} ${baiJamJuree.variable} ${anton.variable}`}
      >
        <UserProvider>
          <main>{children}</main>
        </UserProvider>
      </body>
    </html>
  );
}
